# resolution: [1024, 768]
# offset: [vodorovna, svisla]
resolution: [2024, 768]
camera_source: 1
mail_subject: "Moutarde-Diaphane"
mail_cc: ['mjirik@kky.zcu.cz', "muzejnoc@kky.zcu.cz"]
mail_from: "muzejnoc@kky.zcu.cz"
mail_preamble: ""
compensation: True
watermark: {
    'impath': "./images/ZCM logo_male_neg.png",
    'offset': [10, 400],
    'zoom': 1.0}
flip: True
cut_right: 150
cut_left: 15
erosion_kernel_size: 11
blur_kernel_size: 11
blur_sigma : 11

images: [{
    'background': None,
    'foreground': {
        'impath': 'images/D6-12_small.png',
        'offset': [0, 0],
        'zoom': 1.3},
    'camera_zoom': 1.0,
    'camera_offset': [0, 0],
    'camera_rgb2xyz': [
        1.0, 0.0, 0.0, 0.0,
        0.0, 1.0, 0.0, 0.0,
        0.0, 0.0, 1.0, 0.0],
    },{
    'name': "Reklama na hořčici",
    'background': {
        'impath': 'images/plakat_b.png',
        'offset': [200, 0],
        'zoom': 1.3},
    'foreground': {
        'impath': 'images/plakat_f.png',
        'offset': [200, 0],
        'zoom': 1.3},
    'camera_zoom': 1.3,
    'camera_offset': [-250, -30],
    'camera_rgb2xyz': [
        1.0, 0.0, 0.0, 0.0,
        0.0, 1.0, 0.0, 0.0,
        0.0, 0.0, 1.0, 0.0],
    },{
    'name': "Na plovárně",
    'background': None,
    'foreground': {
        'impath': 'images/D6-12_small.png',
        'offset': [0, 0],
        'zoom': 1.5},
    'camera_zoom': 0.8,
    'camera_offset': [200, 230],
    'camera_rgb2xyz': [
        0.60, 0.25, 0.15, 0.0,
        0.30, 0.55, 0.15, 0.0,
        0.30, 0.25, 0.45, 0.0],
    },{
    'name': "Stavba muzea",
    'background': {
        'impath': 'images/D16-2stavba_muzea.jpg',
        'offset': [0, 0],
        'zoom': 0.2},
    'foreground': None,
    'camera_zoom': 0.3,
    'camera_offset': [300, 300],
    'camera_rgb2xyz': [
        1.0, 0.0, 0.0, 0.0,
        0.0, 1.0, 0.0, 0.0,
        0.0, 0.0, 1.0, 0.0],
    },{
    'name': "Plzeňské korzo",
    'background': {
        'impath': 'images/D 10-33.tif',
        'offset': [0, 0],
        'zoom': 0.2},
    'foreground': None,
    'camera_zoom': 0.4,
    'camera_offset': [200, 270],
    'camera_rgb2xyz': [
        1.0, 0.0, 0.0, 0.0,
        0.0, 1.0, 0.0, 0.0,
        0.0, 0.0, 1.0, 0.0],
    },{
    'name': "Trhy na náměstí",
    'background': {
        'impath': 'images/D6-58.tif',
        'offset': [0, 0],
        'zoom': 0.2},
    'foreground': None,
    'camera_zoom': 0.3,
    'camera_offset': [300, 300],
    'camera_rgb2xyz': [
        1.0, 0.0, 0.0, 0.0,
        0.0, 1.0, 0.0, 0.0,
        0.0, 0.0, 1.0, 0.0],
    }
]
