resolution: [640, 480]


images: [{
    'background': None,
    'foreground': {
        'impath': 'images/D6-12_small.png',
        'offset': [0, 0],
        'zoom': 1.3},
    'camera_zoom': 1.0,
    'camera_offset': [0, 0],

    },{
    'background': {
        'impath': 'images/plakat_b.png',
        'offset': [0, 0],
        'zoom': 1.3},
    'foreground': {
        'impath': 'images/plakat_f.png',
        'offset': [0, 0],
        'zoom': 1.3},
    'camera_zoom': 1.0,
    'camera_offset': [0, 0]
    },{
    'pk': NONE,
    'background': None,
    'foreground': {
        'impath': 'images/D6-12_small.png',
        'offset': [0, 0],
        'zoom': 1.3},
    'camera_zoom': 0.4,
    'camera_offset': [200, 200],
    },{
    'background': {
        'impath': 'images/D6-58.tif',
        'offset': [0, 0],
        'zoom': 0.2},
    'foreground': None,
    'camera_zoom': 0.4,
    'camera_offset': [200, 200],
    }
]
