resolution: [1024, 768]
camera_source: -1
mail_subject: "Moutarde-Diaphane"
mail_cc: ['mjirik@kky.zcu.cz']
mail_from: 'zelezny@kky.zcu.cz'
mail_preamble: ""


images: [{
    'background': None,
    'foreground': {
        'impath': 'images/D6-12_small.png',
        'offset': [0, 0],
        'zoom': 1.3},
    'camera_zoom': 1.0,
    'camera_offset': [0, 0],
    'camera_rgb2xyz': [
        1.0, 0.0, 0.0, 0.0,
        0.0, 1.0, 0.0, 0.0,
        0.0, 0.0, 1.0, 0.0],
    },{
    'background': {
        'impath': 'images/plakat_b.png',
        'offset': [0, 0],
        'zoom': 1.3},
    'foreground': {
        'impath': 'images/plakat_f.png',
        'offset': [0, 0],
        'zoom': 1.3},
    'camera_zoom': 1.0,
    'camera_offset': [0, 0],
    'camera_rgb2xyz': [
        1.0, 0.0, 0.0, 0.0,
        0.0, 1.0, 0.0, 0.0,
        0.0, 0.0, 1.0, 0.0],
    },{
    'background': None,
    'foreground': {
        'impath': 'images/D6-12_small.png',
        'offset': [0, 0],
        'zoom': 1.3},
    'camera_zoom': 0.4,
    'camera_offset': [200, 200],
    'camera_rgb2xyz': [
        0.60, 0.25, 0.15, 0.0,
        0.30, 0.55, 0.15, 0.0,
        0.30, 0.25, 0.45, 0.0],
    },{
    'background': {
        'impath': 'images/D6-58.tif',
        'offset': [0, 0],
        'zoom': 0.2},
    'foreground': None,
    'camera_zoom': 0.4,
    'camera_offset': [200, 200],
    'camera_rgb2xyz': [
        0.0, 1.0, 0.0, 0.0,
        0.0, 0.0, 1.0, 0.0,
        1.0, 0.0, 0.0, 0.0],
    }
]
